/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_YunxingLib */

#ifndef _Included_com_example_myapplication_YunxingLib
#define _Included_com_example_myapplication_YunxingLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_YunxingLib
 * Method:    runYunxingFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_YunxingLib_runYunxingFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
